apparticulos/urls.py
from django.conf.urls import url, patterns
from django.contrib import admin
from apparticulos import views
from django.contrib.auth.decorators import login_required

urlpatterns =  patterns('',
    # url(r'^admin/', admin.site.urls),
    url(r'lista$', login_required(views.listaArticulos.as_view()), name = 'articulosLista'),
    url(r'listadoc/$', login_required(views.listaArticulosUnDoc.as_view()), name = 'articulosListaunDocumento'),
    url(r'edita/(?P<pk>\d+)$', login_required(views.editaArticulos.as_view()), name = 'articulosEdita'),
    url(r'elimina/(?P<pk>\d+)$', login_required(views.eliminaArticulos.as_view()), name = 'articulosElimina'),
    url(r'agrega$', login_required(views.agregaArticulos.as_view()), name = 'articulosAgrega'),
                        )

chatbot/urls.py
from django.conf.urls import patterns, include, url
from chatbot.views import *
from django.contrib.auth.views import login, logout_then_login
#from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',

    # Examples:
    # url(r'^$', 'chatbot.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^accounts/login/', login,{'template_name':'index.html'}, name='login'),
    url(r'^logout/',logout_then_login, name='logout'),
    url(r'^sinonimos/', include('appsinonimos.urls', namespace='sinonimos')),
    url(r'^diccionario/', include('appdiccionario.urls', namespace='diccionario')),
    url(r'^keywords/', include('appkeywords.urls', namespace='keywords')),
    url(r'^predefinidas/', include('apppredefinidas.urls', namespace='predefinidas')),
    url(r'^documentos/', include('appdocumentos.urls', namespace='documentos')),
    url(r'^articulos/', include('apparticulos.urls', namespace='articulos')),
    url(r'^usuarios/', include('appusuarios.urls', namespace='usuarios')),
    url(r'^$', main, name='home'),

    url(r'^navbar',navbar),
    url(r'^processmessage/$', process_message),
    url(r'^contact/$', contact),
    url(r'^populate/$', populate_database),
    url(r'^contact/submit/', send_contact),
#    url(r'^documentos/lista$', ListaDocumentos.as_view(), name='listadocumentos'),
#    url(r'^documentos/detalle$', DetallesDocumento.as_view(), name='detalledocumento'),
)

apparticulos/models.py
from django.db import models
from appdocumentos.models import Documento
# Create your models here.

class Articulo(models.Model):
    idarticulo = models.AutoField(primary_key = True)
    iddocumento = models.ForeignKey(Documento, db_column='iddocumento')
    tipo = models.CharField(max_length=30,choices=[('articulo', 'Articulo'), ('anexo', 'Anexo'),('considerando', 'Considerando')])
    capitulo = models.CharField(max_length=200)
    texto = models.TextField()
    numero = models.IntegerField()
    class Meta:
        db_table = 'reglamentacion\".\"articulos'
        managed = False

apparticulos/forms.py
from django import forms
from apparticulos.models import Articulo

class ArticuloForm(forms.ModelForm):
    class Meta:
        model = Articulo
        fields = [
            'iddocumento',
            'tipo',
            'capitulo',
            'numero',
            'texto',
            ]
        labels = {
            'iddocumento':'IdDocumento',
            'tipo':'Tipo',
            'capitulo':'Capitulo',
            'numero':'Numero',
            'texto':'Texto',
            }
        widgets = {
            'iddocumento':forms.TextInput(attrs = {"class":"form-control", "readonly":"readonly"}),
            'tipo': forms.Select(),
            'capitulo':forms.TextInput(attrs = {"class":"form-control", "autofocus":"autofocus"}),
            'numero':forms.TextInput(attrs={"class":"form-control"}),
            'texto':forms.TextInput(attrs = {"class":"form-control"}),
            }

apparticulos/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, UpdateView, CreateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from apparticulos.models import Articulo
from apparticulos.forms import ArticuloForm
from django.db.models import Q

class listaArticulos(ListView):
    model = Articulo
    template_name = 'articulo_lista.html'
    paginate_by = 15

    def get_queryset(self):
        filtro = self.request.GET.get('filtro', '')
        if filtro == '':
            queryset = Articulo.objects.all().order_by('idarticulo')
        else:
            queryset = Articulo.objects.all().order_by('idarticulo').filter(Q(idarticulo__icontains = filtro) | Q(tipo__icontains = filtro)| Q(capitulo__icontains = filtro)| Q(numero__icontains = filtro)| Q(texto__icontains = filtro))
        return queryset

    def get_context_data(self, **kwargs):
        context = super(listaArticulos, self).get_context_data(**kwargs)
        context['filtro'] = self.request.GET.get('filtro', '')
        return context

    # queryset = Sinonimo.objects.all().filter(palabra = filtro)
class listaArticulosUnDoc(ListView):
    #model = Articulo con request o contex
    template_name = 'articulo_lista1Documento.html'
    paginate_by = 15
    def get_queryset(self):
        iddoc = self.request.GET.get('id',None)
        filtro = self.request.GET.get('filtro', '')
        if filtro == '':
            queryset = Articulo.objects.order_by('iddocumento_id').filter(iddocumento_id=iddoc)
        else:
            queryset = Articulo.objects.all().order_by('idarticulo').filter(iddocumento_id=iddoc).filter(Q(idarticulo__icontains = filtro) | Q(tipo__icontains = filtro)| Q(capitulo__icontains = filtro)| Q(numero__icontains = filtro)| Q(texto__icontains = filtro))
        return queryset

    def get_context_data(self, **kwargs):
        context = super(listaArticulosUnDoc, self).get_context_data(**kwargs)
        context['filtro'] = self.request.GET.get('filtro', '')
        context['id']=self.request.GET.get('id',None)
        return context

    # queryset = Sinonimo.objects.all().filter(palabra = filtro)

class editaArticulos(UpdateView):
    model = Articulo
    form_class = ArticuloForm
    template_name = 'articulo_edita.html'
    success_url = reverse_lazy('articulos:articulosLista')

class agregaArticulos(CreateView):
    model = Articulo

    #Articulo.objects.filter(iddocumento_id=iddoc)
    #iddoc = self.request.GET.get('id', None)
    form_class = ArticuloForm
    template_name = 'articulo_agrega.html'
    success_url = reverse_lazy('articulos:articulosLista')
    iddoc=0
    def get_initial(self):
        inicial=super().get_initial()
        #self.object.iddocumento=1
        inicial['iddocumento']=self.request.GET.get('iddoc', None)
        return inicial
        #self.iddoc = self.request.GET.get('iddoc', None)

class eliminaArticulos(DeleteView):
    model = Articulo
    template_name = 'articulo_elimina.html'
    success_url = reverse_lazy('articulo:articulosLista')

apparticulos/templates/articulo_agrega.html
{% extends 'base.html' %}
{% block content %}
<div>
    		<form method="post">
			{% csrf_token %}
			{% for field in form %}
			<div class = "row">
				<div class="col-md-8 col-md-offset-2">
					<div class="form-group">
						{{field.label}}
						{{field}}
					</div>
				</div>
			</div>
			{% endfor %}
			<div class = "row">
				<div class="col-md-8 col-md-offset-2">
					<div class="form-group">
						<button class="btn btn-primary" type="submit">Guardar</button>
					</div>
				</div>
			</div>
    		</form>

</div>
{%endblock%}

apparticulos/templates/articulo_edita.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <form class="form" action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <br>
        <button type="submit"
            class="btn btn-primary"
            id="guardar"
            value="save"><span ></span> Guardar</button>
    </form>
</div>

{% endblock %}

apparticulos/templates/articulo_elimina.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form class="form" action="" method="POST">
        {% csrf_token %}
        <button type="submit"
        class="btn btn-primary"
        id="eliminar"
        value="save"><span ></span> Eliminar</button>
    </form>
</div>
{%endblock%}

apparticulos/templates/articulo_lista.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md">
        <h3>Articulos
            <a class="btn btn-success btn-circle m-1" href="{% url 'articulos:articulosAgrega' %}"><i class="fas fa-plus"></i></a>
        </h3>
    </div>
    <form class="form-inline" method="GET" action="{% url 'articulos:articulosLista' %}">
        <div class="md-form my-0 justify-content-center">
            <input type="text" class="form-control" placeholder="Buscar" id="cuadroBusqueda" value="{{filtro}}" name="filtro">
        </div>
    </form>
</div>
<div class="row">
    <table class="table table-striped table-sm table-bordered table-responsive-sm">
        <thead class="thead-dark">
            <tr>
                <th class="text-center">ID art</th>
                <th class="text-center">ID doc</th>
                <th class="text-center">Tipo</th>
                <th class="text-center">Capitulo</th>
                <th class="text-center">Numero</th>
                <th class="text-center">Texto</th>
                <th class="text-center"></th>
            </tr>
        </thead>
        <tbody>
            {% for documento in object_list %}
            <tr>
                <td class="text-center">{{ articulo.idarticulo }}</td>
                <td class="text-center">{{ articulo.iddocumento.iddocumento }}</td>
                <td class="text-center">{{ articulo.tipo }}</td>
                <td class="text-center">{{ articulo.capitulo}}</td>
                <td class="text-center">{{ articulo.numero }}</td>
                <td class="text-justify">{{ articulo.texto }}</td>
                <td class="text-center tambutton">
                    <a class="btn btn-primary btn-circle m-1" href="{% url 'articulos:articulosEdita' pk=articulo.idarticulo %}"><i class="fas fa-edit"></i></a>
                    <a class="btn btn-danger btn-circle m-1" href="{% url 'articulos:articulosElimina' pk=articulo.idarticulo %}"><i class="fas fa-trash-alt"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% if is_paginated %}
	<nav>
	<ul class="pagination pagination-circle justify-content-center pg-bluegrey ">
		{% if page_obj.has_previous %}
			<li  class="page-item"><a class="page-link" href="?filtro={{ filtro }}&page={{ page_obj.previous_page_number }}">&laquo;</a></li>
		{% else %}
			<li class="page-item disabled"><span>&laquo;</span></li>
		{% endif %}
		{% for i in paginator.page_range %}
		{% if page_obj.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
		{% if forloop.counter < 7 %}
			<li class="page-item"><a class="page-link" href="?filtro={{ filtro }}&page={{ i }}">{{ i }}</a></li>
			{% endif %}
		{% endif %}
		{% endfor %}
		{% if page_obj.has_next %}
			<li class="page-item"><a class="page-link" href="?filtro={{ filtro }}&page={{ page_obj.next_page_number }}">&raquo;</a></li>
		{% else %}
			<li class="page-item disabled"><span class="page-link">&raquo;</span></li>
		{% endif %}
	</ul>
	</nav>
	{% endif %}
{% endblock %}

apparticulos/templates/articulo_lista1documento.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md">
        <h3>Articulos
            <a class="btn btn-success btn-circle m-1" href="{% url 'articulos:articulosAgrega' %}?iddoc={{id}}"><i class="fas fa-plus"></i></a>
        </h3>
    </div>
    <form class="form-inline" method="GET" action="{% url 'articulos:articulosListaunDocumento' %}">
        <div class="md-form my-0 justify-content-center">
            <input type="text" class="form-control" placeholder="Buscar" id="cuadroBusqueda" value="{{filtro}}" name="filtro">
            <input type="hidden" class="form-control" id="nombre" value="{{id}}" name="id">
        </div>
    </form>
</div>
<div class="row">
    <table class="table table-striped table-sm table-bordered table-responsive-sm">
        <thead class="thead-dark">
            <tr>
                <th class="text-center">ID art</th>
                <th class="text-center">ID doc</th>
                <th class="text-center">Tipo</th>
                <th class="text-center">Capitulo</th>
                <th class="text-center">Numero</th>
                <th class="text-center">Texto</th>
                <th class="text-center"></th>
            </tr>
        </thead>
        <tbody>
            {% for articulo in object_list %}
            <tr>
                <td class="text-center">{{ articulo.idarticulo }}</td>
                <td class="text-center">{{ articulo.iddocumento.iddocumento }}</td>
                <td class="text-center">{{ articulo.tipo }}</td>
                <td class="text-center">{{ articulo.capitulo}}</td>
                <td class="text-center">{{ articulo.numero }}</td>
                <td class="text-justify">{{ articulo.texto }}</td>
                <td class="text-center tambutton">
                    <a class="btn btn-primary btn-circle m-1" href="{% url 'articulos:articulosEdita' pk=articulo.idarticulo %}"><i class="fas fa-edit"></i></a>
                    <a class="btn btn-danger btn-circle m-1" href="{% url 'articulos:articulosElimina' pk=articulo.idarticulo %}"><i class="fas fa-trash-alt"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% if is_paginated %}
	<nav>
	<ul class="pagination pagination-circle justify-content-center pg-bluegrey ">
		{% if page_obj.has_previous %}
			<li  class="page-item"><a class="page-link" href="?filtro={{ filtro }}&page={{ page_obj.previous_page_number }}&id={{id}}">&laquo;</a></li>
		{% else %}
			<li class="page-item disabled"><span>&laquo;</span></li>
		{% endif %}
		{% for i in paginator.page_range %}
		{% if page_obj.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
		{% if forloop.counter < 7 %}
			<li class="page-item"><a class="page-link" href="?filtro={{ filtro }}&page={{ i }}&id={{id}}">{{ i }}</a></li>
			{% endif %}
		{% endif %}
		{% endfor %}
		{% if page_obj.has_next %}
			<li class="page-item"><a class="page-link" href="?filtro={{ filtro }}&page={{ page_obj.next_page_number }}&id={{id}}">&raquo;</a></li>
		{% else %}
			<li class="page-item disabled"><span class="page-link">&raquo;</span></li>
		{% endif %}
	</ul>
	</nav>
	{% endif %}
{% endblock %}