appdiccionario/urls.py
from django.conf.urls import url, patterns
from chatbot.views import *
from appdiccionario.views import Listadiccionario
from appdiccionario.views import Editardiccionario
from appdiccionario.views import Eliminardiccionario
from appdiccionario.views import Agregardiccionario
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',

    # Examples:
    # url(r'^$', 'chatbot.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'lista$',login_required(Listadiccionario.as_view()),name='Diccionariolista'),
    url(r'editar/(?P<pk>\d+)$',login_required(Editardiccionario.as_view()), name='Diccionarioeditar'),
    url(r'eliminar/(?P<pk>\d+)$',login_required(Eliminardiccionario.as_view()), name='Diccionarioeliminar'),
    url(r'agregar$',login_required(Agregardiccionario.as_view()), name='Diccionarioagregar'),
                       )

chatbot/urls.py
from django.conf.urls import patterns, include, url
from chatbot.views import *
from django.contrib.auth.views import login, logout_then_login
#from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',

    # Examples:
    # url(r'^$', 'chatbot.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^accounts/login/', login,{'template_name':'index.html'}, name='login'),
    url(r'^logout/',logout_then_login, name='logout'),
    url(r'^sinonimos/', include('appsinonimos.urls', namespace='sinonimos')),
    url(r'^diccionario/', include('appdiccionario.urls', namespace='diccionario')),
    url(r'^keywords/', include('appkeywords.urls', namespace='keywords')),
    url(r'^predefinidas/', include('apppredefinidas.urls', namespace='predefinidas')),
    url(r'^documentos/', include('appdocumentos.urls', namespace='documentos')),
    url(r'^articulos/', include('apparticulos.urls', namespace='articulos')),
    url(r'^usuarios/', include('appusuarios.urls', namespace='usuarios')),
    url(r'^$', main, name='home'),

    url(r'^navbar',navbar),
    url(r'^processmessage/$', process_message),
    url(r'^contact/$', contact),
    url(r'^populate/$', populate_database),
    url(r'^contact/submit/', send_contact),
#    url(r'^documentos/lista$', ListaDocumentos.as_view(), name='listadocumentos'),
#    url(r'^documentos/detalle$', DetallesDocumento.as_view(), name='detalledocumento'),
)

appdiccionario/models.py
from django.db import models

# Create your models here.

class Diccionario(models.Model):
    id=models.AutoField(primary_key=True)
    palabra=models.CharField(max_length=30)
    porter=models.CharField(max_length=30)
    class Meta:
        db_table = 'reglamentacion\".\"diccionario'
        managed=False

appdiccionario/forms.py
from django import forms
from appdiccionario.models import Diccionario

class DiccionarioForm(forms.ModelForm):
    class Meta:
        model=Diccionario
        fields=['palabra',
                'porter',]
        labels={'palabra':'Palabra',
                'porter':'Porter',}
        widgets={'palabra':forms.TextInput(attrs={'class':'form-control'}),
                 'porter':forms.TextInput(attrs={'class':'form-control'}),}

appdiccionario/views.py
from django.core.urlresolvers import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from appdiccionario.models import Diccionario
from appdiccionario.forms import DiccionarioForm
from django.views.generic import CreateView, ListView,UpdateView, DeleteView
from django.db.models import Q

class Listadiccionario(ListView):
    model = Diccionario
    template_name = 'diccionario_lista.html'
    paginate_by = 15

    def get_queryset(self):
        filtro = self.request.GET.get('filtro', '')
        if filtro == '':
            queryset = Diccionario.objects.all().order_by('palabra')
        else:
            queryset = Diccionario.objects.all().order_by('palabra').filter(Q(palabra__icontains = filtro) | Q(porter__icontains = filtro))
        return queryset

    def get_context_data(self, **kwargs):
        context = super(Listadiccionario, self).get_context_data(**kwargs)
        context['filtro'] = self.request.GET.get('filtro', '')
        return context

    # queryset = Sinonimo.objects.all().filter(palabra = filtro)

class Editardiccionario(UpdateView):
    model = Diccionario
    form_class = DiccionarioForm
    template_name = 'diccionario_edita.html'
    success_url = reverse_lazy('diccionario:Diccionariolista')

class Agregardiccionario(CreateView):
    model = Diccionario
    form_class = DiccionarioForm
    template_name = 'diccionario_agrega.html'
    success_url = reverse_lazy('diccionario:Diccionariolista')

class Eliminardiccionario(DeleteView):
    model = Diccionario
    template_name = 'diccionario_elimina.html'
    success_url = reverse_lazy('diccionario:Diccionariolista')

appdiccionario/templates/diccionario_agrega.html
{% extends 'base.html' %}
{% block content %}
<div>
		<form class="form" action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <br>
        <button type="submit"
            class="btn btn-primary"
            id="guardar"
            value="save"><span ></span> Guardar</button>
    </form>
</div>
{% endblock %}

appdiccionario/templates/diccionario_edita.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <form class="form" action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <br>
        <button type="submit"
            class="btn btn-primary"
            id="guardar"
            value="save"><span ></span> Guardar</button>
    </form>
</div>

{% endblock %}

appdiccionario/templates/diccionario_elimina.html
{% extends 'base.html' %}
{% block content %}
<div class="container" align="center">
    <form class="form" action="" method="POST">
        {% csrf_token %}
        <button type="submit"
        class="btn btn-primary"
        id="eliminar"
        value="save"><span ></span> Eliminar</button>
    </form>
</div>
{% endblock %}

appdiccionario/templates/diccionario_lista.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
	<div class="col-md">
        <h3>Diccionario
            <a class="btn btn-success btn-circle m-1" href="{% url 'diccionario:Diccionarioagregar' %}"><i class="fas fa-plus"></i></a>
        </h3>
    </div>
    
        <form class="form-inline" method="GET" action="{% url 'diccionario:Diccionariolista' %}">
        	<div class="md-form my-0 justify-content-center">
            <input type="text" class="form-control" placeholder="Buscar" id="cuadroBusqueda" value="{{filtro}}" name="filtro">
        </div>
        </form>
</div>

<div class="row">
	<table  class="table table-striped table-sm table-bordered table-responsive-sm">
		<thead class="thead-dark">
			<tr>
				<th class="text-center">ID</th>
				<th class="text-center">Palabra</th>
				<th class="text-center">Porter</th>
				<th class="text-center"></th>
			</tr>
		</thead>
		<tbody>

			{% for diccionario in object_list %}
			<tr>
				<td class="text-center">{{ diccionario.id }}</td>
				<td class="text-center">{{ diccionario.palabra }}</td>
				<td class="text-center">{{ diccionario.porter }}</td>
				<td class="text-center tambutton">
					<a class="btn btn-primary btn-circle m-1" href="{% url 'diccionario:Diccionarioeditar' pk=diccionario.id %}"><i class="fas fa-edit"></i></a>
					<a class="btn btn-danger btn-circle m-1" href="{% url 'diccionario:Diccionarioeliminar' pk=diccionario.id %}"><i class="fas fa-trash-alt"></i></a>		
				</td>
			</tr>
			{% endfor %}

		</tbody>
	</table>
</div>

{% if is_paginated %}
	<nav>
	<ul class="pagination pagination-circle justify-content-center pg-bluegrey ">

		{% if page_obj.has_previous %}
			<li  class="page-item"><a class="page-link" href="?filtro={{ filtro }}&page={{ page_obj.previous_page_number }}">&laquo;</a></li>
		{% else %}
			<li class="page-item disabled"><span>&laquo;</span></li>
		{% endif %}
		{% for i in paginator.page_range %}
		{% if page_obj.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
		{% if forloop.counter < 7 %}
			<li class="page-item"><a class="page-link" href="?filtro={{ filtro }}&page={{ i }}">{{ i }}</a></li>
			{% endif %}
		{% endif %}
		{% endfor %}
		{% if page_obj.has_next %}
			<li class="page-item"><a class="page-link" href="?filtro={{ filtro }}&page={{ page_obj.next_page_number }}">&raquo;</a></li>
		{% else %}
			<li class="page-item disabled"><span class="page-link">&raquo;</span></li>
		{% endif %}

	</ul>
	</nav>
	{% endif %}


{% endblock %}