appdiccionario/urls.py
from django.conf.urls import url, patterns
from chatbot.views import *
from appdiccionario.views import Listadiccionario
from appdiccionario.views import Editardiccionario
from appdiccionario.views import Eliminardiccionario
from appdiccionario.views import Agregardiccionario
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',

    # Examples:
    # url(r'^$', 'chatbot.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'lista$',login_required(Listadiccionario.as_view()),name='Diccionariolista'),
    url(r'editar/(?P<pk>\d+)$',login_required(Editardiccionario.as_view()), name='Diccionarioeditar'),
    url(r'eliminar/(?P<pk>\d+)$',login_required(Eliminardiccionario.as_view()), name='Diccionarioeliminar'),
    url(r'agregar$',login_required(Agregardiccionario.as_view()), name='Diccionarioagregar'),
                       )

appdocumentos/urls.py
from django.conf.urls import patterns, url
from appdocumentos import views
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',

    # Examples:
    # url(r'^$', 'chatbot.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^lista$', login_required(views.ListaDocumentos.as_view()), name='documentoLista'),
    url(r'^detalle/(?P<pk>\d+)$', login_required(views.DetallesDocumento.as_view()), name='documentoDetalle'),
    url(r'agregar$', login_required(views.AgregarDocumento.as_view()),name='DocumentoAgrega'),
    url(r'editar/(?P<pk>\d+)$', login_required(views.EditarDocumento.as_view()),name='DocumentoEdita'),
    url(r'eliminar/(?P<pk>\d+)$', login_required(views.EliminarDocumento.as_view()),name='DocumentoElimina'),
)

appkeywords/urls.py
from django.conf.urls import url, patterns
from django.contrib import admin
from appkeywords import views
from chatbot.views import *
from django.contrib.auth.decorators import login_required

urlpatterns =  patterns('',
    # url(r'^admin/', admin.site.urls),
    url(r'lista$', login_required(views.ListaKeywords.as_view()), name = 'keywordsLista'),
    url(r'edita/(?P<pk>\d+)$', login_required(views.EditaKeywords.as_view()), name = 'keywordsEdita'),
    url(r'elimina/(?P<pk>\d+)$', login_required(views.EliminaKeywords.as_view()), name = 'keywordsElimina'),
    url(r'agrega$', login_required(views.AgregaKeywords.as_view()), name = 'keywordsAgrega'),
                        )

appsinonimos/urls.py
from django.conf.urls import url, patterns
from django.contrib import admin
from appsinonimos import views
from django.contrib.auth.decorators import login_required
urlpatterns =  patterns('',
    # url(r'^admin/', admin.site.urls),
    url(r'lista$', login_required(views.listaSinonimos.as_view()), name = 'sinonimosLista'),
    url(r'edita/(?P<pk>\d+)$', login_required(views.editaSinonimos.as_view()), name = 'sinonimosEdita'),
    url(r'elimina/(?P<pk>\d+)$', login_required(views.eliminaSinonimos.as_view()), name = 'sinonimosElimina'),
    url(r'agrega$', login_required(views.agregaSinonimos.as_view()), name = 'sinonimosAgrega'),
                        )

chatbot/urls.py
from django.conf.urls import patterns, include, url
from chatbot.views import *
from django.contrib.auth.views import login, logout_then_login
#from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',

    # Examples:
    # url(r'^$', 'chatbot.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^accounts/login/', login,{'template_name':'index.html'}, name='login'),
    url(r'^logout/',logout_then_login, name='logout'),
    url(r'^sinonimos/', include('appsinonimos.urls', namespace='sinonimos')),
    url(r'^diccionario/', include('appdiccionario.urls', namespace='diccionario')),
    url(r'^keywords/', include('appkeywords.urls', namespace='keywords')),
    url(r'^predefinidas/', include('apppredefinidas.urls', namespace='predefinidas')),
    url(r'^documentos/', include('appdocumentos.urls', namespace='documentos')),
    url(r'^articulos/', include('apparticulos.urls', namespace='articulos')),
    url(r'^usuarios/', include('appusuarios.urls', namespace='usuarios')),
    url(r'^$', main, name='home'),

    url(r'^navbar',navbar),
    url(r'^processmessage/$', process_message),
    url(r'^contact/$', contact),
    url(r'^populate/$', populate_database),
    url(r'^contact/submit/', send_contact),
#    url(r'^documentos/lista$', ListaDocumentos.as_view(), name='listadocumentos'),
#    url(r'^documentos/detalle$', DetallesDocumento.as_view(), name='detalledocumento'),
)

templates/base.html
<!-- Created: 20/09/2017 by cpank -->
{% load staticfiles %}

<!DOCTYPE HTML>
<html>
  <head>
    <title>Base</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"></link>
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}"></link>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}"></link>


  </head>
  <body >
    {% block menu %}
    {% include 'menu.html' %}
    {% endblock %}

    <div class="container margen">
    {% block content %}
    {% endblock %}  
    </div>
      

      {% block footer %}
      {% include 'pie.html' %}
      {% endblock %}

      <!-- Jquery -->
      <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
      <!-- Bootstrap tooltips -->
      <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
      <!-- Bootstrap core JavaScript -->
      <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
      <!-- MDB core JavaScript -->
      <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
      <!-- Font Awesome -->
      <script type="text/javascript" src="{% static 'js/all.min.js' %}"></script>
      <script src="{% static 'js/main.js' %}"></script>
      
  </body>
</html>

templates/cabecera.html
{% load static %}

<nav class="navbar navbar-light navbar-fixed-top" style="background-color: #306030">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><img src="{% static 'img/ptah-nuevo.png' %}" class="logo"></a>
            <a class="navbar-brand" href="/" style="color: #e0e0e0">PTAH</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
    </div><!-- /.container-fluid -->
</nav>

templates/menu.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
  <div class="navbar-header">
  <a class="navbar-brand" href="/"><img src="{% static 'img/ptah-nuevo.png' %}"  alt="Logo" class="logo"></a>
  <a class="navbar-brand" href="/" style="color: #e0e0e0">PTAH</a>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'documentos:documentoLista' %}">Reglamentacion<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'diccionario:Diccionariolista' %}">Diccionario</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'keywords:keywordsLista' %}">Palabras clave</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sinonimos:sinonimosLista' %}">Sinonimos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'predefinidas:predefinidasLista' %}">Preguntas Predefinidas</a>
      </li>
      <!-- Interfaz del usuario -->
      {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.get_username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'logout' %}">Salir</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Iniciar Sesion</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/pie.html
{% load static %}
<!-- Footer -->
<footer class="page-footer font-small black">

  <!-- Footer Links -->
  <div class="container">

    <!-- Grid row-->
    <div class="row text-center d-flex justify-content-center pt-5 mb-3">

      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="#!">Acerca De</a>
        </h6>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="#!">Contacto</a>
        </h6>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->
    <hr class="rgba-white-light" style="margin: 0 15%;">

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2016 - 2020:
    <a href="#"> GIBD UTN-FRCU</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->