apparticulos/urls.py
from django.conf.urls import url, patterns
from django.contrib import admin
from apparticulos import views
from django.contrib.auth.decorators import login_required

urlpatterns =  patterns('',
    # url(r'^admin/', admin.site.urls),
    url(r'lista$', login_required(views.listaArticulos.as_view()), name = 'articulosLista'),
    url(r'listadoc/$', login_required(views.listaArticulosUnDoc.as_view()), name = 'articulosListaunDocumento'),
    url(r'edita/(?P<pk>\d+)$', login_required(views.editaArticulos.as_view()), name = 'articulosEdita'),
    url(r'elimina/(?P<pk>\d+)$', login_required(views.eliminaArticulos.as_view()), name = 'articulosElimina'),
    url(r'agrega$', login_required(views.agregaArticulos.as_view()), name = 'articulosAgrega'),
                        )

appdocumentos/urls.py
from django.conf.urls import patterns, url
from appdocumentos import views
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',

    # Examples:
    # url(r'^$', 'chatbot.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^lista$', login_required(views.ListaDocumentos.as_view()), name='documentoLista'),
    url(r'^detalle/(?P<pk>\d+)$', login_required(views.DetallesDocumento.as_view()), name='documentoDetalle'),
    url(r'agregar$', login_required(views.AgregarDocumento.as_view()),name='DocumentoAgrega'),
    url(r'editar/(?P<pk>\d+)$', login_required(views.EditarDocumento.as_view()),name='DocumentoEdita'),
    url(r'eliminar/(?P<pk>\d+)$', login_required(views.EliminarDocumento.as_view()),name='DocumentoElimina'),
)

chatbot/urls.py
from django.conf.urls import patterns, include, url
from chatbot.views import *
from django.contrib.auth.views import login, logout_then_login
#from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',

    # Examples:
    # url(r'^$', 'chatbot.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^accounts/login/', login,{'template_name':'index.html'}, name='login'),
    url(r'^logout/',logout_then_login, name='logout'),
    url(r'^sinonimos/', include('appsinonimos.urls', namespace='sinonimos')),
    url(r'^diccionario/', include('appdiccionario.urls', namespace='diccionario')),
    url(r'^keywords/', include('appkeywords.urls', namespace='keywords')),
    url(r'^predefinidas/', include('apppredefinidas.urls', namespace='predefinidas')),
    url(r'^documentos/', include('appdocumentos.urls', namespace='documentos')),
    url(r'^articulos/', include('apparticulos.urls', namespace='articulos')),
    url(r'^usuarios/', include('appusuarios.urls', namespace='usuarios')),
    url(r'^$', main, name='home'),

    url(r'^navbar',navbar),
    url(r'^processmessage/$', process_message),
    url(r'^contact/$', contact),
    url(r'^populate/$', populate_database),
    url(r'^contact/submit/', send_contact),
#    url(r'^documentos/lista$', ListaDocumentos.as_view(), name='listadocumentos'),
#    url(r'^documentos/detalle$', DetallesDocumento.as_view(), name='detalledocumento'),
)

appdocumentos/models.py
from django.db import models
from datetime import date

# Create your models here.
class Documento(models.Model):
    iddocumento = models.AutoField(primary_key = True)
    nro = models.CharField(max_length = 20)
    fecha = models.DateField(default=date.today())
    descripcion=models.CharField(max_length=50, null=False)
    texto=models.TextField()
    tipo =models.CharField(max_length=30, choices=[('ley', 'Ley'),('reglamentacion informal', 'Reglamentacion Informal'),('ordenanza', 'Ordenanza'),('jurisprudencia', 'Jurisprudencia'),('acta', 'Acta'),('resolucion', 'Resolucion'),('estatuto', 'Estatuto'),('otra', 'Otra')])
    class Meta:
        db_table = 'reglamentacion\".\"documentos'
        managed = False

appdocumentos/forms.py
from django import forms
from appdocumentos.models import Documento
import datetime
class DocumentoForm(forms.ModelForm):
    class Meta:
        model=Documento
       #fields es campos a poner en el formulario
        fields=[
            'nro',
            'tipo',
            'fecha',
            'descripcion',
            'texto',
        ]
        #Labels van a ser las etiquetas que va a tomar ese campo
        labels=[{
            'nro':'Numero De Documento',
            'tipo': 'Tipo',
            'fecha':'Fecha',
            'descripcion':'Titulo',
            'texto':'Texto',
            }]
        #el formato de las cajas de texto
        widgets=[{
            'nro':forms.TextInput(attrs = {'class':'form-control'}),
            'fecha':forms.DateField(widget=forms.DateInput(format=('%d/%m/%y'),attrs={'placeholder':'2000-12-30'})),
            'descripcion':forms.TextInput(attrs = {'class':'form-control'}),
            'tipo':forms.Select(),
            'texto':forms.TextInput(attrs = {'class':'form-control'}),
        }]

appdocumentos/views.py
from django.shortcuts import render
from appdocumentos.models import Documento
from appdocumentos.forms import DocumentoForm
from django.db.models import Q
from django.views.generic import CreateView, ListView, DetailView,UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

# Create your views here.
class ListaDocumentos(ListView):
    model = Documento
    template_name = 'documentos_lista.html'
    paginate_by = 15

    def get_queryset(self):
        filtro = self.request.GET.get('filtro', '')
        if filtro == '':
            queryset = Documento.objects.all().order_by('iddocumento')
        else:
            queryset = Documento.objects.all().order_by('iddocumento').filter(Q(descripcion__icontains = filtro) | Q(nro__icontains = filtro)| Q(tipo__icontains = filtro))
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ListaDocumentos, self).get_context_data(**kwargs)
        context['filtro'] = self.request.GET.get('filtro', '')
        return context

class DetallesDocumento(DetailView):
    model = Documento
    template_name = 'documentos_detalle.html'

class AgregarDocumento(CreateView):
    model= Documento
    form_class= DocumentoForm
    template_name='documentos_agrega.html'
    success_url= reverse_lazy('documentos:documentoLista')

class EditarDocumento(UpdateView):
    model= Documento
    form_class = DocumentoForm
    template_name = 'documentos_edita.html'
    success_url = reverse_lazy('documentos:documentoLista')

class EliminarDocumento(DeleteView):
    model = Documento
    template_name = 'documentos_elimina.html'
    success_url = reverse_lazy('documentos:documentoLista')

appdocumentos/templates/documentos_agrega (Copia en conflicto de Juan Kitu 2018-06-07).html
{% extends 'base.html' %}
{% block content %}
<div>
		<form class="form" action="" method="POST">
        {% csrf_token %}

            {{ form }}

        <br>
        <button type="submit"
            class="btn btn-primary"
            id="guardar"
            value="save"><span ></span> Guardar</button>
    </form>
</div>
{%endblock%}

appdocumentos/templates/documentos_agrega.html
{% extends 'base.html' %}
{% block content %}
<div>
		<form method="post">
			{% csrf_token %}
			<div class = "row">
				<div class="col-md-8 col-md-offset-2">
					<div class="form-group">
						<label>Numero</label>
						<input class="form-control" type="text" name="nro">
					</div>
				</div>
			</div>

			<div class = "row">
				<div class="col-md-8 col-md-offset-2">
					<div class="form-group">
						<label>Fecha</label>
						<input class="form-control" type="text" name="fecha">
					</div>
				</div>
			</div>

			<div class = "row">
				<div class="col-md-8 col-md-offset-2">
					<div class="form-group">
						<label>Descripcion</label>
						<input class="form-control" type="text" name="descripcion">
					</div>
				</div>
			</div>

			<div class = "row">
				<div class="col-md-8 col-md-offset-2">
					<div class="form-group">
						<label>Tipo</label>
						<select class="form-control" name="tipo">
							{% for value, text in form.fields.tipo.choices %}
							<option value="{{ value }}">{{ text }}</option>
							{% endfor %}
						</select>
					</div>
				</div>
			</div>

			<div class = "row">
				<div class="col-md-8 col-md-offset-2">
					<div class="form-group">
						<label>Texto</label>
						<textarea class="form-control" name="texto" cols="40" rows="10"></textarea>
					</div>
				</div>
			</div>

			<div class = "row">
				<div class="col-md-8 col-md-offset-2">
					<div class="form-group">
						<button class="btn btn-primary" type="submit">Guardar</button>
					</div>
				</div>
			</div>
		</form>
</div>
{%endblock%}

appdocumentos/templates/documentos_detalle.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md">
        <h3>Detalle del Documento
            <a class="btn btn-success btn-circle m-1" href="{% url 'documentos:DocumentoEdita' pk=documento.iddocumento %}"><i class="fas fa-edit"></i></a>
        </h3>
    </div>
</div>

<div class="row">
    <table class="table table-striped table-sm table-bordered table-responsive-sm">
        <thead class="thead-dark">
            <tr>
                <th class="text-center">ID</th>
                <th class="text-center">Número</th>
                <th class="text-center">Tipo</th>
                <th class="text-center">Fecha</th>
                <th class="text-center">Descripción</th>
                <th class="text-center">Texto</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-center">{{ documento.iddocumento }}</td>
                <td class="text-center">{{ documento.nro }}</td>
                <td class="text-center">{{ documento.tipo }}</td>
                <td class="text-center">{{ documento.fecha }}</td>
                <td class="text-center">{{ documento.descripcion }}</td>
                <td class="text-justify">{{ documento.texto }}</td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}

appdocumentos/templates/documentos_edita.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <form class="form" action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <br>
        <button type="submit"
            class="btn btn-primary"
            id="guardar"
            value="save"><span ></span> Guardar</button>
    </form>
</div>

{% endblock %}

appdocumentos/templates/documentos_elimina.html
{% extends 'base.html' %}
{% block content %}
<div class="container" align="center">
    <form class="form" action="" method="POST">
        {% csrf_token %}
        <button type="submit"
        class="btn btn-primary"
        id="eliminar"
        value="save"><span ></span> Eliminar</button>
    </form>
</div>
{% endblock %}

appdocumentos/templates/documentos_lista.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md">
        <h3>Documentos
            <a class="btn btn-success btn-circle m-1" href="{% url 'documentos:DocumentoAgrega' %}"><i class="fas fa-plus"></i></a>
        </h3>
    </div>
    <form class="form-inline" method="GET" action="{% url 'documentos:documentoLista' %}">
        <div class="md-form my-0 justify-content-center">
            <input type="text" class="form-control" placeholder="Buscar" id="cuadroBusqueda" value="{{filtro}}" name="filtro">
        </div>
    </form>
</div>
<div class="row">
    <table class="table table-striped table-sm table-bordered table-responsive-sm">
        <thead class="thead-dark">
            <tr>
                <th class="text-center">ID</th>
                <th class="text-center">Número</th>
                <th class="text-center">Tipo</th>
                <th class="text-center">Fecha</th>
                <th class="text-center">Descripción</th>
                <th class="text-center"></th>
            </tr>
        </thead>
        <tbody>
            {% for documento in object_list %}
            <tr>
                <td class="text-center">{{ documento.iddocumento }}</td>
                <td class="text-center">{{ documento.nro }}</td>
                <td class="text-center">{{ documento.tipo }}</td>
                <td class="text-center">{{ documento.fecha }}</td>
                <td class="text-center">{{ documento.descripcion }}</td>
                <td class="text-center tambutton">
                    <a class="btn btn-primary btn-circle m-1" href="{% url 'documentos:DocumentoEdita' pk=documento.iddocumento %}"><i class="fas fa-edit"></i></a>
                    <a class="btn btn-info btn-circle m-1" href="{% url 'documentos:documentoDetalle' pk=documento.iddocumento %}"><i class="fas fa-info-circle"></i></i></a>
                    <a class="btn btn-danger btn-circle m-1" href="{% url 'documentos:DocumentoElimina' pk=documento.iddocumento %}"><i class="fas fa-trash-alt"></i></a>
                    <a class="btn btn-warning btn-circle m-1" href="{% url 'articulos:articulosListaunDocumento'%}?id={{documento.iddocumento}}"><i class="fas fa-book"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% if is_paginated %}
	<nav>
	<ul class="pagination pagination-circle justify-content-center pg-bluegrey ">
		{% if page_obj.has_previous %}
			<li  class="page-item"><a class="page-link" href="?filtro={{ filtro }}&page={{ page_obj.previous_page_number }}">&laquo;</a></li>
		{% else %}
			<li class="page-item disabled"><span>&laquo;</span></li>
		{% endif %}
		{% for i in paginator.page_range %}
		{% if page_obj.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
		{% if forloop.counter < 7 %}
			<li class="page-item"><a class="page-link" href="?filtro={{ filtro }}&page={{ i }}">{{ i }}</a></li>
			{% endif %}
		{% endif %}
		{% endfor %}
		{% if page_obj.has_next %}
			<li class="page-item"><a class="page-link" href="?filtro={{ filtro }}&page={{ page_obj.next_page_number }}">&raquo;</a></li>
		{% else %}
			<li class="page-item disabled"><span class="page-link">&raquo;</span></li>
		{% endif %}
	</ul>
	</nav>
	{% endif %}
{% endblock %}